apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gestion-stocks
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: gestion-stocks
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234
  MYSQL_DATABASE: gestion_stocks
  MYSQL_USER: stocks_user
  MYSQL_PASSWORD: stocks1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: gestion-stocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gestion-stocks
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
